+JHS+ Fr.e $\swarrow$
#Arreglos y clases
## Matrices:
 Arreglos de datos en un espacio bidimensional de *m* x *n*.
 \begin{equation}
\begin{matrix}
1 & 2 & 3 & x^2\\
5 & 8 & 13 & y^n\\
21 & 34 & 55 & z^5\\
2&4&8&6
\end{matrix}
\end{equation}

In [3]:
#Una lista que contiene otras listas.
A=[[1,2,3],[4,5,6],[7,8,9]]
print (A)
type(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [8]:
#Otra lista de listas
B=[[21,34,40],[71,45,16],[13,20,79]]
A+B
#Concatenar las listas (las está pegando)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 45, 16], [13, 20, 79]]

In [7]:
2*A #Duplica la lista.

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
# A[0,0] Forma incorrecta de ingresar a la lista X
A[1][2] #Forma correcta de ingresar a la lista


6

##Vectores y listas

In [19]:
L=A[0]
M=B[0]
print (L)
L+M

[1, 2, 3]


[1, 2, 3, 21, 34, 40]

In [22]:
a=L[0]
a
b=M[0]
#Una vez seleccionada el único datod de la lista, entonces y solo entonces se puede sumar.
a+b

22

In [23]:
#Boleano
a==1

True

###Suma de "Vectores"


In [27]:
len(L)==len(M)
suma=[L[0]+M[0],L[1]+M[1],L[2]+M[2]]
suma
#Suma

[22, 36, 43]

In [34]:
suma=[L[i]+M[i] for i in range(3)]
print (f"suma:{suma}")

suma:[22, 36, 43]


----------


#### Funciones globales
la función para hacer funciones es `def` que se cierra con un debug (`print` o `return`)

In [36]:
def Hola():
  print("Hola, calcula pi")

In [37]:
Hola()

Hola, calcula pi


In [39]:
def Adios(s,n):
  print(f"Adios es un gusto {s} y tengo {n} años")

In [42]:
Adios("Xavier", 26)
#Reucerda poner " " para todo string y poner siempre la f para invocar la función

Adios es un gusto Xavier y tengo 26 años


In [51]:
I=[i for i in range(10)]
def par():
  for x in range(len(I)):
    if x%2==0:
       print(f"{x} es par")
    else:
       print(f"{x} es impar")

In [52]:
par()

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


----


#### Vector a travez de funciones

In [56]:
def suma_vectorial(L,M):
  x=[L[i]+M[i]for i in range(len(L))]
  #El return es para que regrese la varible
  return x

In [60]:
L=[1,2,3]
M=[21,34,40]

suma_vectorial(L,M)

[22, 36, 43]

###Módulos o librerías
$ \phi $

In [61]:
import math
# el *  son todas las funciones
from math import *

In [66]:
sqrt(225)

15.0

In [65]:
e

2.718281828459045

## *El módulo NumPy*
* la función `array`.

In [68]:
#array lista en vector
import numpy as np
L_vector= np.array(L)
M_vector=np.array(M)
L_vector+M_vector

array([22, 36, 43])

In [73]:
C=[9,2,2,2,3,3,2,17,2]
A= [8,1,1,1,2,2,1,16,1]
len(A)==len(C)
C_matrix= np.array(C). reshape(3,3)
A_matrix= np.array(A). reshape(3,3)
print(C_matrix)
print(A_matrix)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [75]:
C_matrix @ A_matrix

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])

In [76]:
A_matrix @ C_matrix

array([[76, 36, 21],
       [17, 42, 12],
       [43, 67, 52]])